application: chromeutility
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /updates.xml
  static_files: updates.xml
  upload: updates.xml

- url: .*
  script: main.py
